content/people/elijahvoigt.mkd

spelling correction

---

content/blog/backups.mkd

turn the backups email into a blog post too

---

.gitignore
content/events/20150929_wk1.mkd
content/events/20151006_wk2.mkd
content/events/20151013_wk3.mkd
content/events/20151020_wk4.mkd
content/events/20151027_wk5.mkd
content/events/20151103_wk6.mkd
content/events/20151110_wk7.mkd
content/events/20151117_wk8.mkd
content/events/20151124_wk9.mkd
content/home.mkd
event_template.dist

@lucywyman @edunham @mythmon @rettigs  Thoughts?

Added fall 2015 events pages, updated homepage

---

content/events/20151013_wk3.mkd
content/events/20151020_wk4.mkd
content/events/20151027_wk5.mkd
content/events/20151103_wk6.mkd

Add first four weeks of LUG events

---

.travis.yml

http://docs.travis-ci.com/user/migrating-from-legacy/
This will make travis runs quicker.

don't use legacy travis

---

content/events/20160105_wk1.mkd
content/events/20160112_wk2.mkd
content/events/20160119_wk3.mkd
content/events/20160126_wk4.mkd
content/events/20160202_wk5.mkd
content/events/20160209_wk6.mkd
content/events/20160216_wk7.mkd
content/events/20160223_wk8.mkd
content/events/20160301_wk9.mkd

Please suggest changes. @rettigs @lucywyman

Winter 2016 Initial Schedule Commit

---

content/events/20160211.mkd
content/home.mkd

Added more front-and-center info about CoreOS Night

---

content/events/20160209_wk6.mkd
content/events/20160216_wk7.mkd
content/events/20160301_wk9.mkd

Added nibz to speaking list, move things around

---

content/events/20160329_wk1.mkd
content/events/20160405_wk2.mkd
content/events/20160412_wk3.mkd
content/events/20160419_wk4.mkd
content/events/20160426_wk5.mkd
content/events/20160503_wk6.mkd
content/events/20160510_wk7.mkd
content/events/20160517_wk8.mkd
content/events/20160524_wk9.mkd

Added skeleton agenda for spring 2016

---

templates/home.html

Link upcoming events to event page

---

templates/metadata.html

Add timestamps to blog posts

---

content/guides/irc.mkd

Fix link + typos

---

content/guides/reading.mkd

Add living reading list doc

---

content/guides/github.mkd

Add essential github guide

---

content/events/2016/fall2016/20161018_wk4.mkd
content/events/2016/fall2016/20161025_wk5.mkd
content/events/2016/fall2016/20161101_wk6.mkd
content/events/2016/fall2016/20161108_wk7.mkd
content/events/2016/fall2016/20161129_wk10.mkd

Not quite done yet, but this is what I have so far.

Wrote events for LUG after the takeover.

---

content/events/2016/fall2016/20161108_wk7.mkd
content/events/2016/fall2016/20161115_wk8.mkd
content/events/2016/fall2016/20161122_wk9.mkd

Move the REST talk down a week to make room for a surprise talk from pop!
And add Raspberry Pi night on week 9.

Add events for weeks 7-9

---

content/events/2017/winter2017/20170110_wk1.mkd
content/events/2017/winter2017/20170117_wk2.mkd
content/events/2017/winter2017/20170124_wk3.mkd
content/events/2017/winter2017/20170131_wk4.mkd
content/events/2017/winter2017/20170207_wk5.mkd
content/events/2017/winter2017/20170214_wk6.mkd
content/events/2017/winter2017/20170221_wk7.mkd
content/events/2017/winter2017/20170228_wk8.mkd
content/events/2017/winter2017/20170307_wk9.mkd
content/events/2017/winter2017/20170314_wk10.mkd

Add the events we've done so far, a couple future events, and some
placeholders for the unscheduled weeks.
Week 2 description based on my email.
Week 3 description based on Connor's email.
It was really weird writing about the past events in future tense.
I just thought you should know that.

Add Winter 2017 events

---

content/events/2017/fall2017/20171024_wk5.mkd

Added info for the filesystem meeting mentioned in slack.  Check out the website and make sure it's all right since it's the first time I'm doing this.

Added filesystem meeting for 10/24

---

content/events/2017/fall2017/20171010_wk3.mkd
content/events/2017/fall2017/20171017_wk4.mkd
content/events/2017/fall2017/20171024_wk5.mkd

Added missing weeks information.

Website update

---

content/events/2017/fall2017/20171114_wk8.mkd

Add eli link

---

content/events/2018/winter2018/20180109_wk1.mkd

Added the meeting for this week

Added this weeks meeting

---

content/home.mkd

I was sitting outside the room not knowing you were right next door!

Fix room number

---

content/guides/barcamp_bbq.mkd

@lucywyman @magical @ErichKramer pls

Barcamp BBQ Guide

---

content/events/2019/fall2019/20180925_wk1.mkd
content/events/2019/fall2019/20181002_wk2.mkd
content/events/2019/fall2019/20181009_wk3.mkd
content/events/2019/fall2019/20181016_wk4.mkd
content/events/2019/fall2019/20181023_wk5.mkd
content/events/2019/fall2019/20181030_wk6.mkd
content/events/2019/fall2019/20181106_wk7.mkd
content/events/2019/fall2019/20181113_wk8.mkd
content/events/2019/fall2019/20181120_wk9.mkd
content/events/2019/fall2019/20181127_wk10.mkd
content/people/chandlerpeterson.mkd
content/people/danielgrocki.mkd
content/people/lanceroy.mkd
content/people/monicaholliday.mkd
content/people/vancekerry.mkd

Also reorganized contacts a little bit

Fixed room numbers

---

content/events/2019/winter2019/20190108_wk1.mkd
content/events/2019/winter2019/20190115_wk2.mkd
content/events/2019/winter2019/20190122_wk3.mkd
content/events/2019/winter2019/20190129_wk4.mkd
content/events/2019/winter2019/20190205_wk5.mkd
content/events/2019/winter2019/20190212_wk6.mkd
content/events/2019/winter2019/20190219_wk7.mkd
content/events/2019/winter2019/20190226_wk8.mkd
content/events/2019/winter2019/20190305_wk9.mkd
content/events/2019/winter2019/20190312_wk10.mkd

I've added weeks 1 and 2, everything else is tbd at the moment. I figured it would be good to at least have out next event up and we can fix the tbds later.

added events for the term

---

content/events.mkd
content/events/2020/fall2020/20191001_wk1.mkd
content/events/2020/fall2020/20191008_wk2.mkd
content/events/2020/fall2020/20191015_wk3.mkd
content/events/2020/fall2020/20191022_wk4.mkd
content/events/2020/fall2020/20191029_wk5.mkd
content/events/2020/fall2020/20191105_wk6.mkd
content/events/2020/fall2020/20191112_wk7.mkd
content/events/2020/fall2020/20191119_wk8.mkd
content/events/2020/fall2020/20191126_wk9.mkd
content/events/2020/fall2020/20191203_wk10.mkd

Also changed events to show 10 events per page (one terms worth)

updated events for Fall 2019
